version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: 
          name: Run all tests
          command: yarn test
      - run:
          name: Signal tests are done
          command: console.log('Tests are done')
